export default [
  {
    title: "Software Engineer",
    category: "Technology",
    description: "Design and develop software applications and systems.",
    averageSalary: "₹4-20 LPA",
    jobGrowth: "15-20% annually",
    educationRequired: "B.Tech/B.E in Computer Science",
    keySkills: ["Programming", "Problem Solving"],
    workEnvironment: "IT Companies, Startups, Remote",
    popularCourses: ["CSE", "IT"],
    careerLevels: ["Junior Developer", "Senior Developer", "Tech Lead"],
    streamRequired: ["Science (PCM)", "Computer Science"],
  },
  {
    title: "Software Engineer",
    category: "Healthcare",
    description: "Develop healthcare software applications.",
    averageSalary: "₹3-15 LPA",
    jobGrowth: "12-18% annually",
    educationRequired: "B.Tech/B.E in IT/CS or Bioinformatics",
    keySkills: ["Programming", "Healthcare IT", "Problem Solving"],
    workEnvironment: "Hospitals, Healthcare IT Companies",
    popularCourses: ["CSE", "Bioinformatics"],
    careerLevels: ["Junior Developer", "Senior Developer", "Tech Lead"],
    streamRequired: ["Science (PCB)", "Computer Science"],
  },
  {
    title: "Medical Doctor",
    category: "Healthcare",
    description: "Diagnose and treat patients, conduct medical research, and contribute to healthcare advancement.",
    averageSalary: "₹6-30 LPA",
    jobGrowth: "12-18% annually",
    educationRequired: "MBBS + MD/MS specialization",
    keySkills: ["Medical Knowledge", "Empathy", "Decision Making", "Communication"],
    workEnvironment: "Hospitals, Clinics, Research Centers",
    popularCourses: ["MBBS", "BDS", "BAMS", "BHMS"],
    careerLevels: ["Junior Doctor", "Specialist", "Consultant", "Department Head"],
    streamRequired: ["Science (PCB)", "Biology"]
  },
  {
    title: "Chartered Accountant",
    category: "Finance",
    description: "Manage financial records, provide tax advice, and ensure compliance with financial regulations.",
    averageSalary: "₹5-25 LPA",
    jobGrowth: "8-12% annually",
    educationRequired: "CA qualification after Class 12",
    keySkills: ["Accounting", "Financial Analysis", "Tax Knowledge", "Audit"],
    workEnvironment: "Accounting Firms, Corporate Offices, Self-practice",
    popularCourses: ["CA (Chartered Accountancy)", "CS (Company Secretary)", "CMA"],
    careerLevels: ["Article Assistant", "Associate", "Manager", "Partner"],
    streamRequired: ["Commerce", "Any Stream"]
  },
  {
    title: "Graphic Designer",
    category: "Creative",
    description: "Create visual content for digital and print media using design software and artistic skills.",
    averageSalary: "₹2-10 LPA",
    jobGrowth: "10-15% annually",
    educationRequired: "BFA/B.Des in Graphic Design",
    keySkills: ["Design Software", "Creativity", "Visual Communication", "Typography"],
    workEnvironment: "Design Studios, Ad Agencies, Freelance",
    popularCourses: ["Graphic Design", "Visual Communication", "Fine Arts"],
    careerLevels: ["Junior Designer", "Senior Designer", "Art Director", "Creative Director"],
    streamRequired: ["Any Stream", "Arts"]
  },
  {
    title: "Civil Engineer",
    category: "Engineering",
    description: "Design, construct, and maintain infrastructure projects like buildings, roads, and bridges.",
    averageSalary: "₹3-15 LPA",
    jobGrowth: "8-12% annually",
    educationRequired: "B.Tech/B.E in Civil Engineering",
    keySkills: ["Structural Design", "Project Management", "CAD Software", "Problem Solving"],
    workEnvironment: "Construction Sites, Offices, Government Agencies",
    popularCourses: ["Civil Engineering", "Environmental Engineering", "Structural Engineering"],
    careerLevels: ["Junior Engineer", "Project Engineer", "Site Manager", "Project Manager"],
    streamRequired: ["Science (PCM)", "Mathematics"]
  },
  {
    title: "Psychologist",
    category: "Healthcare",
    description: "Study human behavior and mental processes to help individuals overcome psychological challenges.",
    averageSalary: "₹3-12 LPA",
    jobGrowth: "12-18% annually",
    educationRequired: "BA/MA in Psychology",
    keySkills: ["Counseling", "Research", "Empathy", "Communication"],
    workEnvironment: "Hospitals, Clinics, Schools, Private Practice",
    popularCourses: ["Psychology", "Clinical Psychology", "Counseling Psychology"],
    careerLevels: ["Assistant Psychologist", "Clinical Psychologist", "Senior Psychologist", "Director"],
    streamRequired: ["Arts", "Science", "Any Stream"]
  },
  {
    title: "Digital Marketing Specialist",
    category: "Marketing",
    description: "Promote products and services using digital channels like social media, search engines, and websites.",
    averageSalary: "₹3-15 LPA",
    jobGrowth: "20-25% annually",
    educationRequired: "BBA/MBA in Marketing",
    keySkills: ["SEO/SEM", "Social Media", "Analytics", "Content Creation"],
    workEnvironment: "Marketing Agencies, Startups, Corporate",
    popularCourses: ["Digital Marketing", "Mass Communication", "MBA Marketing"],
    careerLevels: ["Marketing Executive", "Digital Marketing Manager", "Growth Manager", "CMO"],
    streamRequired: ["Any Stream", "Commerce"]
  },
  {
    title: "Data Scientist",
    category: "Technology",
    description: "Analyze complex data to extract insights and support business decision-making using statistical methods.",
    averageSalary: "₹6-25 LPA",
    jobGrowth: "25-30% annually",
    educationRequired: "B.Tech/M.Tech in Computer Science/Statistics",
    keySkills: ["Python/R", "Machine Learning", "Statistics", "Data Visualization"],
    workEnvironment: "Tech Companies, Consulting Firms, Research Labs",
    popularCourses: ["Data Science", "Statistics", "Computer Science", "Mathematics"],
    careerLevels: ["Data Analyst", "Data Scientist", "Senior Data Scientist", "Chief Data Officer"],
    streamRequired: ["Science (PCM)", "Mathematics", "Computer Science"]
  },
  {
    title: "Lawyer",
    category: "Legal",
    description: "Provide legal advice, represent clients in court, and ensure justice through legal expertise.",
    averageSalary: "₹3-20 LPA",
    jobGrowth: "8-12% annually",
    educationRequired: "LLB (5 years) after Class 12",
    keySkills: ["Legal Research", "Communication", "Critical Thinking", "Negotiation"],
    workEnvironment: "Law Firms, Courts, Corporate Legal Departments",
    popularCourses: ["LLB", "BA LLB", "BBA LLB", "LLM"],
    careerLevels: ["Junior Associate", "Associate", "Senior Associate", "Partner"],
    streamRequired: ["Any Stream", "Arts", "Commerce"]
  }
];
